add comment because this really burned me (#32)
I was in the process of working on a template and wanted to add an **AWS::Serverless::Function** so I use the `sam build` command to build my code with using the `-b ./` command, to my surprise on the second run it complained that the template didn't exist, excuse me?  
Upon closer inspection, anything in the `./` directory was gone.

This would have been nice to know, maybe I would have or would not have read it, but when I go back and see if something said "WARNING THIS HAPPENS" I wouldn't be so bummed, but I came very close to losing a lot of work because this `rm -rf`ed a lot of uncommited changes.

Thanks

```
❯ ls -la
total 8
drwxrwxrwx@  6 bkillian  staff   192 Dec 26 03:51 .
drwxrwxrwx@  9 bkillian  staff   288 Dec 26 03:49 ..
drwxr-xr-x   2 bkillian  staff    64 Dec 26 03:51 test
❯ touch test/test.txt
❯ ls -la test
total 0
drwxr-xr-x  3 bkillian  staff   96 Dec 26 03:52 .
drwxrwxrwx@ 6 bkillian  staff  192 Dec 26 03:51 ..
-rw-r--r--  1 bkillian  staff    0 Dec 26 03:52 test.txt
❯ sam build -b ./test/ -u -t templates/home-unifi.yml --profile trailmix --debug
2019-12-26 03:52:34 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
...
...
...
Build Failed
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt
❯ ls -la test
total 0
drwxr-xr-x  2 bkillian  staff   64 Dec 26 03:52 .
drwxrwxrwx@ 6 bkillian  staff  192 Dec 26 03:52 ..
```